import './globals.css'
import { ApolloWrapper } from "@/helper/apollo-wrapper";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
      <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  )
}
